// Copyright 2018-2026 the Deno authors. MIT license.

//! The base internal inplementation of structuredClone, which are
//! StructuredSerializeInternal/StructuredDeserialize
//! StructuredSerializeWithTransfer/StructuredDeserializeWithTransfer
//! does not correspond one-to-one with the steps in the WHATWG spec.
//!
//! Recursive serialization and deserialization of ECMAScript built-in object
//! graphs is delegated to [v8::ValueSerializer] and [v8::ValueDeserializer].
//! This preserves cycles, shared references, and V8's representation of built-ins
//! such as Array, Map, Set, Date, and more.
//!
//! The JavaScript Host platform of Deno should implements host(platform) objects
//! that V8 does not know about.
//! It includes host objects such as Blob is a [Serializable] interface or
//! OffscreenCanvas is a [Transferable] interface, and more.
//!
//! To achieve this, it helps to understand beforehand how the JS Host
//! should override the behavior of the V8 serializer/deserializer.
//! https://source.chromium.org/chromium/chromium/src/+/main:v8/include/v8-value-serializer.h

use std::any::Any;
use std::any::TypeId;
use std::borrow::Cow;
use std::collections::HashMap;
use std::sync::Arc;

use deno_core::v8;
use deno_core::v8::ValueDeserializerHelper;
use deno_core::v8::ValueSerializerHelper;
use deno_error::JsErrorBox;

use crate::JsRuntime;
use crate::cppgc::GarbageCollected;
use crate::webidl::ContextFn;
use crate::webidl::WebIdlConverter;
use crate::webidl::WebIdlError;
use crate::webidl::WebIdlErrorKind;

pub enum StructuredCloneTransferData<T> {
  ArrayBuffer(v8::SharedRef<v8::BackingStore>),
  HostObject(T),
}

pub struct StructuredSerializeWithTransferResult<T> {
  pub serialized: Vec<u8>,
  pub transfer_data_holders: Vec<StructuredCloneTransferData<T>>,
}

pub struct StructuredDeserializeWithTransferResult<'s> {
  pub deserialized: v8::Local<'s, v8::Value>,
  pub transferred_values: Vec<v8::Local<'s, v8::Value>>,
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/value-serializer.cc
// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/v8_script_value_serializer.cc
// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/v8_script_value_deserializer.cc
// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/serialization_tag.h

/// Deno wraps V8's serialized data in an embedder-controlled version envelope:
///
///   0xFE | wire format version:uint32(varint) | V8 header | V8 payload
///
/// The outer version covers Deno host-object tags and payloads, while the inner
/// V8 header carries V8's independently versioned wire format. The envelope is
/// consumed before constructing the V8 deserializer. The single-byte marker is
/// distinct from V8's 0xFF version header.
const EMBEDDER_ENVELOPE_TAG: u8 = 0xFE;

/// Increment this for each incompatible change to the wire format.
///
/// Version of the Deno-controlled structured-clone envelope and host-object
/// payloads.
/// It must keep
/// Persisted structured-clone data must remain readable by newer
/// runtimes.
/// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/serialized_script_value.h;l=118-153
pub const WIRE_FORMAT_VERSION: u32 = 1;

// Host-object tags are written as exactly one raw byte before the type-specific
// payload.
// Values are permanent wire identifiers:
//
// Never renumber, reorder by implicit discriminant, or reuse a retired value.
// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/serialization_tag.h
#[derive(Clone, Copy, Eq, Hash, PartialEq)]
#[repr(u8)]
pub enum SerializationTag {
  /// Serializing order:
  ///
  /// settings of ImageDataSerializationTag: u32,
  /// ImageDataSerializationTag::End: u32,
  /// width: u32,
  /// height: u32,
  /// data: V8-serialized Uint8ClampedArray/Float16Array
  ImageData = b'#',
  /// offset: u64 (fixed width, network order) from buffer start
  /// size: u32 (fixed width, network order)
  TrailerOffset = 0xFE,
  /// version: u32 -> Uses this as the file version.
  Version = 0xFF,
}

// V8's WriteUint32 uses a base-128 varint: each byte contributes seven value
// bits and the high bit indicates that another byte follows. Four bytes carry
// 28 bits, so a u32 may use a fifth byte, whose value is limited to four bits.
const VARINT_VALUE_MASK: u8 = 0x7F;
const VARINT_CONTINUATION_BIT: u8 = 0x80;
const VARINT_VALUE_BITS_PER_BYTE: usize = 7;
const U32_VARINT_MAX_BYTES: usize = 5;
const U32_VARINT_LAST_BYTE_MAX: u8 = 0x0F;

/// Marker generated by `#[webidl(serializable)]` for Web IDL interfaces that
/// declare the `[Serializable]` extended attribute.
pub trait WebIdlSerializable {}

/// Marker generated by `#[webidl(transferable)]` for Web IDL interfaces that
/// declare the `[Transferable]` extended attribute.
///
/// This marker records the IDL contract only. The interface must separately
/// implement `StructuredCloneTransferable`, because validation, detachment,
/// transfer data, and receiving steps are specific to each platform object.
pub trait WebIdlTransferable {}

/// The base [[Detached]] slot carried by Web IDL.
///
/// Serializable/Transferable interfaces which has [[Detached]] slot
/// should also implement this trait.
/// Their serialization must fail once the object has been detached.
pub trait StructuredCloneDetached: GarbageCollected + 'static {
  /// Returns the state of this object's [[Detached]] internal slot.
  fn was_detached(&self) -> bool;

  /// Sets this object's [[Detached]] internal slot after transfer succeeds.
  fn detach(&self);
}

/// Common structured-clone behavior for a Web IDL platform object.
pub trait StructuredCloneHostObject:
  GarbageCollected + Sized + 'static
{
  /// Returns whether this interface is exposed in `target_realm`.
  fn is_exposed<'s, 'i>(
    scope: &mut v8::PinScope<'s, 'i>,
    target_realm: v8::Local<'s, v8::Context>,
  ) -> bool;
}

/// Serialization and deserialization steps for a Web IDL `[Serializable]`
/// platform object.
///
/// The wire tag is deliberately not part of this trait. Tags are maintained in
/// one embedder-owned enum so duplicate discriminants are rejected at compile
/// time and retired values remain reserved.
pub trait StructuredCloneSerializable:
  StructuredCloneHostObject + WebIdlSerializable
{
  /// Spec sometimes outline a specific order of operations,
  /// however unless there are specific dependencies each other,
  /// we don't need to keep up to it.
  ///
  /// e.g.,
  ///
  /// ImageData objects are serializable objects. Their serialization steps, given value and serialized, are:
  /// 1. Set serialized.[[Data]] to the sub-serialization of the value of value's data attribute.
  /// 2. Set serialized.[[Width]] to the value of value's width attribute.
  /// 3. ...
  /// https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#imagedata
  fn write_structured_clone_payload<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    context: v8::Local<'s, v8::Context>,
    serializer: &dyn v8::ValueSerializerHelper,
  ) -> Option<bool>;

  /// Keep up the backward compatibility when the wire format version changes
  /// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/v8_script_value_deserializer.cc;l=472-485
  fn read_structured_clone_payload<'s, 'i>(
    scope: &mut v8::PinScope<'s, 'i>,
    context: v8::Local<'s, v8::Context>,
    deserializer: &dyn v8::ValueDeserializerHelper,
    wire_format_version: u32,
  ) -> Option<Self>;
}

/// Transfer and transfer-receiving steps for a Web IDL `[Transferable]`
/// platform object. Transfer data is out-of-band and is never persisted in the
/// structured-clone wire payload.
pub trait StructuredCloneTransferable:
  StructuredCloneHostObject
  + WebIdlTransferable
  + StructuredCloneDetached
  + Sized
  + 'static
{
  type TransferData: 'static;

  /// Performs the interface's transfer steps without changing [[Detached]].
  fn transfer<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
  ) -> Result<Self::TransferData, JsErrorBox>;

  fn receive<'s, 'i>(
    scope: &mut v8::PinScope<'s, 'i>,
    data: Self::TransferData,
  ) -> Result<Self, JsErrorBox>;
}

pub fn is_structured_clone_host_object<'s, 'i, T: StructuredCloneHostObject>(
  scope: &mut v8::PinScope<'s, 'i>,
  object: v8::Local<'s, v8::Object>,
) -> bool {
  crate::cppgc::try_unwrap_cppgc_object::<T>(scope, object.into()).is_some()
}

pub fn write_structured_clone_host_object<
  's,
  'i,
  T: StructuredCloneSerializable,
>(
  scope: &mut v8::PinScope<'s, 'i>,
  context: v8::Local<'s, v8::Context>,
  object: v8::Local<'s, v8::Object>,
  serializer: &dyn v8::ValueSerializerHelper,
) -> Option<bool> {
  let value = crate::cppgc::try_unwrap_cppgc_object::<T>(scope, object.into())?;
  // SAFETY: `object` remains live for this V8 serializer callback.
  let value = unsafe { value.as_ref() };
  value.write_structured_clone_payload(scope, context, serializer)
}

pub fn read_structured_clone_host_object<
  's,
  'i,
  T: StructuredCloneSerializable,
>(
  scope: &mut v8::PinScope<'s, 'i>,
  context: v8::Local<'s, v8::Context>,
  deserializer: &dyn v8::ValueDeserializerHelper,
  wire_format_version: u32,
) -> Option<v8::Local<'s, v8::Object>> {
  let value = T::read_structured_clone_payload(
    scope,
    context,
    deserializer,
    wire_format_version,
  )?;
  // FIXME: throw DataCloneError if its None
  Some(crate::cppgc::make_cppgc_object(scope, value))
}

pub fn structured_clone_object_was_detached<
  's,
  'i,
  T: StructuredCloneDetached,
>(
  scope: &mut v8::PinScope<'s, 'i>,
  object: v8::Local<'s, v8::Object>,
) -> Result<bool, JsErrorBox> {
  let value = crate::cppgc::try_unwrap_cppgc_object::<T>(scope, object.into())
    .ok_or_else(|| data_clone_error("Transferable has an invalid brand"))?;
  // SAFETY: `object` remains live for the duration of this synchronous call.
  let value = unsafe { value.as_ref() };
  Ok(value.was_detached())
}

pub fn transfer_structured_clone_host_object<
  's,
  'i,
  T: StructuredCloneTransferable,
>(
  scope: &mut v8::PinScope<'s, 'i>,
  object: v8::Local<'s, v8::Object>,
) -> Result<T::TransferData, JsErrorBox> {
  let value = crate::cppgc::try_unwrap_cppgc_object::<T>(scope, object.into())
    .ok_or_else(|| data_clone_error("Transferable has an invalid brand"))?;
  // SAFETY: `object` remains live for the duration of this synchronous call.
  let value = unsafe { value.as_ref() };
  value.transfer(scope)
}

pub fn detach_structured_clone_object<'s, 'i, T: StructuredCloneDetached>(
  scope: &mut v8::PinScope<'s, 'i>,
  object: v8::Local<'s, v8::Object>,
) -> Result<(), JsErrorBox> {
  let value = crate::cppgc::try_unwrap_cppgc_object::<T>(scope, object.into())
    .ok_or_else(|| data_clone_error("Transferable has an invalid brand"))?;
  // SAFETY: `object` remains live for the duration of this synchronous call.
  let value = unsafe { value.as_ref() };
  value.detach();
  Ok(())
}

pub fn receive_structured_clone_host_object<
  's,
  'i,
  T: StructuredCloneTransferable,
>(
  scope: &mut v8::PinScope<'s, 'i>,
  data: T::TransferData,
) -> Result<v8::Local<'s, v8::Object>, JsErrorBox> {
  let value = T::receive(scope, data)?;
  Ok(crate::cppgc::make_cppgc_object(scope, value))
}

/// Hooks for platform objects whose serialization is defined by the embedder.
///
/// The hooks are called by V8 while it walks a single object graph, so they
/// must write and read exactly one host-object record per invocation.
pub trait StructuredCloneHostObjectRegistry {
  type TransferData;

  /// Version of the embedder-controlled wire format wrapped around V8 data.
  fn wire_format_version(&self) -> u32;

  fn is_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> bool;

  fn write_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    context: v8::Local<'s, v8::Context>,
    object: v8::Local<'s, v8::Object>,
    transfer_id: Option<u32>,
    serializer: &dyn v8::ValueSerializerHelper,
  ) -> Option<bool>;

  fn read_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    context: v8::Local<'s, v8::Context>,
    deserializer: &dyn v8::ValueDeserializerHelper,
    wire_format_version: u32,
    transferred_host_objects: &[v8::Global<v8::Object>],
  ) -> Option<v8::Local<'s, v8::Object>>;

  fn is_transferable_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<bool, JsErrorBox>;

  /// Returns the transferable object's [[Detached]] state after serialization.
  fn was_detached_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<bool, JsErrorBox>;

  fn transfer_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<Self::TransferData, JsErrorBox>;

  fn detach_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<(), JsErrorBox>;

  fn receive_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    target_realm: v8::Local<'s, v8::Context>,
    data: Self::TransferData,
  ) -> Result<v8::Local<'s, v8::Object>, JsErrorBox>;
}

type IsExposedHandler =
  for<'s, 'i> fn(&mut v8::PinScope<'s, 'i>, v8::Local<'s, v8::Context>) -> bool;

type WriteHostObjectHandler = for<'s, 'i> fn(
  &mut v8::PinScope<'s, 'i>,
  v8::Local<'s, v8::Context>,
  v8::Local<'s, v8::Object>,
  &dyn v8::ValueSerializerHelper,
) -> Option<bool>;

type ReadHostObjectHandler =
  for<'s, 'i> fn(
    &mut v8::PinScope<'s, 'i>,
    v8::Local<'s, v8::Context>,
    &dyn v8::ValueDeserializerHelper,
    u32,
  ) -> Option<v8::Local<'s, v8::Object>>;

type WasDetachedHandler = for<'s, 'i> fn(
  &mut v8::PinScope<'s, 'i>,
  v8::Local<'s, v8::Object>,
) -> Result<bool, JsErrorBox>;

type TransferHostObjectHandler =
  for<'s, 'i> fn(
    &mut v8::PinScope<'s, 'i>,
    v8::Local<'s, v8::Object>,
  ) -> Result<StructuredCloneRegistryTransferData, JsErrorBox>;

type DetachHostObjectHandler = for<'s, 'i> fn(
  &mut v8::PinScope<'s, 'i>,
  v8::Local<'s, v8::Object>,
) -> Result<(), JsErrorBox>;

type ReceiveTransferHandler =
  for<'s, 'i> fn(
    &mut v8::PinScope<'s, 'i>,
    Box<dyn Any>,
  ) -> Result<v8::Local<'s, v8::Object>, JsErrorBox>;

type TypeMatchHandler =
  for<'s> fn(&mut v8::Isolate, v8::Local<'s, v8::Object>) -> bool;

#[derive(Clone, Copy)]
struct SerializableHandler {
  tag: u8,
  write: WriteHostObjectHandler,
  read: ReadHostObjectHandler,
}

#[derive(Clone, Copy)]
struct TransferableHandler {
  tag: u8,
  transfer: TransferHostObjectHandler,
}

#[derive(Clone, Copy)]
struct DetachedHandler {
  was_detached: WasDetachedHandler,
  detach: DetachHostObjectHandler,
}

#[derive(Clone, Copy)]
struct HostObjectHandler {
  matches: TypeMatchHandler,
  is_exposed: IsExposedHandler,
  detached: Option<DetachedHandler>,
  serializable: Option<SerializableHandler>,
  transferable: Option<TransferableHandler>,
}

#[derive(Clone, Copy)]
enum HostObjectTagHandler {
  Serialized {
    read: ReadHostObjectHandler,
    is_exposed: IsExposedHandler,
  },
  Transferred {
    matches: TypeMatchHandler,
    is_exposed: IsExposedHandler,
  },
}

const HOST_OBJECT_TAG_COUNT: usize = u8::MAX as usize + 1;

#[derive(Clone)]
struct StructuredCloneRegistryInner {
  handlers_by_tag: [Option<HostObjectTagHandler>; HOST_OBJECT_TAG_COUNT],
  // TODO: Replace TypeId dispatch with stable Web IDL interface descriptors
  // once Deno has descriptor-based typed unwrap and inheritance support.
  handlers_by_type: HashMap<TypeId, HostObjectHandler>,
}

/// Registry for platform objects participating in structured cloning.
///
/// Wire tags are permanent identifiers. Callers must not renumber or reuse a
/// tag after its format has shipped.
#[derive(Clone)]
pub struct StructuredCloneRegistry {
  inner: Arc<StructuredCloneRegistryInner>,
}

impl Default for StructuredCloneRegistry {
  fn default() -> Self {
    Self::new()
  }
}

impl StructuredCloneRegistry {
  pub fn new() -> Self {
    Self {
      inner: Arc::new(StructuredCloneRegistryInner {
        handlers_by_tag: [None; HOST_OBJECT_TAG_COUNT],
        handlers_by_type: HashMap::new(),
      }),
    }
  }

  fn register_handler<T: 'static>(&mut self, handler: HostObjectHandler) {
    let inner = Arc::make_mut(&mut self.inner);
    assert!(
      inner
        .handlers_by_type
        .insert(TypeId::of::<T>(), handler)
        .is_none(),
      "structured clone type registered twice"
    );
    if let Some(serializable) = handler.serializable {
      assert!(
        inner.handlers_by_tag[serializable.tag as usize]
          .replace(HostObjectTagHandler::Serialized {
            read: serializable.read,
            is_exposed: handler.is_exposed,
          })
          .is_none(),
        "structured clone tag registered twice"
      );
    }
    if let Some(transferable) = handler.transferable {
      assert!(
        inner.handlers_by_tag[transferable.tag as usize]
          .replace(HostObjectTagHandler::Transferred {
            matches: handler.matches,
            is_exposed: handler.is_exposed,
          })
          .is_none(),
        "structured clone tag registered twice"
      );
    }
  }

  pub fn register_serializable<T: StructuredCloneSerializable>(
    &mut self,
    tag: u8,
  ) {
    self.register_handler::<T>(HostObjectHandler {
      matches: registered_type_matches::<T>,
      is_exposed: structured_clone_host_object_is_exposed::<T>,
      detached: None,
      serializable: Some(SerializableHandler {
        tag,
        write: write_structured_clone_host_object::<T>,
        read: read_structured_clone_host_object::<T>,
      }),
      transferable: None,
    });
  }

  pub fn register_transferable<T: StructuredCloneTransferable>(
    &mut self,
    tag: u8,
  ) {
    self.register_handler::<T>(HostObjectHandler {
      matches: registered_type_matches::<T>,
      is_exposed: structured_clone_host_object_is_exposed::<T>,
      detached: Some(DetachedHandler {
        was_detached: structured_clone_object_was_detached::<T>,
        detach: detach_structured_clone_object::<T>,
      }),
      serializable: None,
      transferable: Some(TransferableHandler {
        tag,
        transfer: transfer_registered_host_object::<T>,
      }),
    });
  }

  pub fn register_serializable_transferable<
    T: StructuredCloneSerializable + StructuredCloneTransferable,
  >(
    &mut self,
    serialized_tag: u8,
    transferred_tag: u8,
  ) {
    self.register_handler::<T>(HostObjectHandler {
      matches: registered_type_matches::<T>,
      is_exposed: structured_clone_host_object_is_exposed::<T>,
      detached: Some(DetachedHandler {
        was_detached: structured_clone_object_was_detached::<T>,
        detach: detach_structured_clone_object::<T>,
      }),
      serializable: Some(SerializableHandler {
        tag: serialized_tag,
        write: write_structured_clone_host_object::<T>,
        read: read_structured_clone_host_object::<T>,
      }),
      transferable: Some(TransferableHandler {
        tag: transferred_tag,
        transfer: transfer_registered_host_object::<T>,
      }),
    });
  }
}

pub struct StructuredCloneRegistryTransferData {
  is_exposed: IsExposedHandler,
  receive: ReceiveTransferHandler,
  data: Box<dyn Any>,
}

fn structured_clone_host_object_is_exposed<
  's,
  'i,
  T: StructuredCloneHostObject,
>(
  scope: &mut v8::PinScope<'s, 'i>,
  target_realm: v8::Local<'s, v8::Context>,
) -> bool {
  T::is_exposed(scope, target_realm)
}

fn registered_type_matches<T: GarbageCollected + 'static>(
  scope: &mut v8::Isolate,
  object: v8::Local<v8::Object>,
) -> bool {
  crate::cppgc::try_unwrap_cppgc_object::<T>(scope, object.into()).is_some()
}

fn registered_host_object_type_id(
  registry: &StructuredCloneRegistry,
  scope: &mut v8::Isolate,
  object: v8::Local<v8::Object>,
) -> Option<TypeId> {
  registry
    .inner
    .handlers_by_type
    .iter()
    .find_map(|(type_id, handler)| {
      (handler.matches)(scope, object).then_some(*type_id)
    })
}

fn transfer_registered_host_object<'s, 'i, T: StructuredCloneTransferable>(
  scope: &mut v8::PinScope<'s, 'i>,
  object: v8::Local<'s, v8::Object>,
) -> Result<StructuredCloneRegistryTransferData, JsErrorBox> {
  Ok(StructuredCloneRegistryTransferData {
    is_exposed: structured_clone_host_object_is_exposed::<T>,
    receive: receive_registered_host_object::<T>,
    data: Box::new(transfer_structured_clone_host_object::<T>(scope, object)?),
  })
}

fn receive_registered_host_object<'s, 'i, T: StructuredCloneTransferable>(
  scope: &mut v8::PinScope<'s, 'i>,
  data: Box<dyn Any>,
) -> Result<v8::Local<'s, v8::Object>, JsErrorBox> {
  let data = data
    .downcast::<T::TransferData>()
    .map_err(|_| data_clone_error("Transfer data has an unexpected type"))?;
  receive_structured_clone_host_object::<T>(scope, *data)
}

fn host_object_not_transferable() -> JsErrorBox {
  data_clone_error("Host object is not transferable")
}

impl StructuredCloneHostObjectRegistry for StructuredCloneRegistry {
  type TransferData = StructuredCloneRegistryTransferData;

  fn wire_format_version(&self) -> u32 {
    WIRE_FORMAT_VERSION
  }

  fn is_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> bool {
    registered_host_object_type_id(self, scope, object).is_some()
  }

  fn write_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    context: v8::Local<'s, v8::Context>,
    object: v8::Local<'s, v8::Object>,
    transfer_id: Option<u32>,
    serializer: &dyn v8::ValueSerializerHelper,
  ) -> Option<bool> {
    let type_id = registered_host_object_type_id(self, scope, object)?;
    let handler = self.inner.handlers_by_type.get(&type_id)?;
    if let Some(transfer_id) = transfer_id {
      let transferable = handler.transferable?;
      serializer.write_raw_bytes(&[transferable.tag]);
      serializer.write_uint32(transfer_id);
      return Some(true);
    }
    let serializable = handler.serializable?;
    if let Some(detached) = handler.detached
      && (detached.was_detached)(scope, object).ok()?
    {
      let message =
        v8::String::new(scope, "Cannot serialize a detached platform object")?;
      let error = v8::Exception::error(scope, message);
      scope.throw_exception(error);
      return None;
    }
    serializer.write_raw_bytes(&[serializable.tag]);
    (serializable.write)(scope, context, object, serializer)
  }

  fn read_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    context: v8::Local<'s, v8::Context>,
    deserializer: &dyn v8::ValueDeserializerHelper,
    wire_format_version: u32,
    transferred_host_objects: &[v8::Global<v8::Object>],
  ) -> Option<v8::Local<'s, v8::Object>> {
    let tag = *deserializer.read_raw_bytes(1)?.first()?;
    match self.inner.handlers_by_tag[tag as usize]? {
      //
      // StructuredDeserialize step 22.2.
      // V8 owns the recursive traversal, so the exposure check is performed
      // when its host-object callback reaches the serializable platform object.
      // https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserialize
      //
      HostObjectTagHandler::Serialized { read, is_exposed } => {
        if !is_exposed(scope, context) {
          throw_interface_not_exposed(scope);
          return None;
        }
        read(scope, context, deserializer, wire_format_version)
      }
      HostObjectTagHandler::Transferred {
        matches,
        is_exposed,
      } => {
        if !is_exposed(scope, context) {
          throw_interface_not_exposed(scope);
          return None;
        }
        let mut transfer_id = 0;
        if !deserializer.read_uint32(&mut transfer_id) {
          return None;
        }
        let object = v8::Local::new(
          scope,
          transferred_host_objects.get(transfer_id as usize)?,
        );
        matches(scope, object).then_some(object)
      }
    }
  }

  fn is_transferable_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<bool, JsErrorBox> {
    let Some(type_id) = registered_host_object_type_id(self, scope, object)
    else {
      return Ok(false);
    };
    Ok(
      self
        .inner
        .handlers_by_type
        .get(&type_id)
        .is_some_and(|handler| handler.transferable.is_some()),
    )
  }

  fn was_detached_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<bool, JsErrorBox> {
    let type_id = registered_host_object_type_id(self, scope, object)
      .ok_or_else(host_object_not_transferable)?;
    let detached = self
      .inner
      .handlers_by_type
      .get(&type_id)
      .and_then(|handler| handler.detached)
      .ok_or_else(host_object_not_transferable)?;
    (detached.was_detached)(scope, object)
  }

  fn transfer_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<Self::TransferData, JsErrorBox> {
    let type_id = registered_host_object_type_id(self, scope, object)
      .ok_or_else(host_object_not_transferable)?;
    let transferable = self
      .inner
      .handlers_by_type
      .get(&type_id)
      .and_then(|handler| handler.transferable)
      .ok_or_else(host_object_not_transferable)?;
    (transferable.transfer)(scope, object)
  }

  fn detach_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Result<(), JsErrorBox> {
    let type_id = registered_host_object_type_id(self, scope, object)
      .ok_or_else(host_object_not_transferable)?;
    let detached = self
      .inner
      .handlers_by_type
      .get(&type_id)
      .and_then(|handler| handler.detached)
      .ok_or_else(host_object_not_transferable)?;
    (detached.detach)(scope, object)
  }

  fn receive_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    target_realm: v8::Local<'s, v8::Context>,
    data: Self::TransferData,
  ) -> Result<v8::Local<'s, v8::Object>, JsErrorBox> {
    // 4.2.
    // https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserializewithtransfer
    if !(data.is_exposed)(scope, target_realm) {
      return Err(data_clone_error(
        "Interface is not exposed in the target realm",
      ));
    }
    (data.receive)(scope, data.data)
  }
}

fn throw_interface_not_exposed(scope: &mut v8::PinScope<'_, '_>) {
  // TODO: Throw a DataCloneError DOMException rather than a plain V8 Error.
  // deno_core cannot directly construct the DOMException provided by deno_web.
  if let Some(message) =
    v8::String::new(scope, "Interface is not exposed in the target realm")
  {
    let error = v8::Exception::error(scope, message);
    scope.throw_exception(error);
  }
}

// V8 owns reference tracking while it serializes a complete object graph.
// Keep Web(Deno) platform specific state here as support is added.
struct V8SerializerDelegate<'a, R> {
  for_storage: bool,
  host_objects: &'a R,
  // Nested host-object values must use the context selected by the caller,
  // not whichever context happens to be current during a V8 callback.
  context: v8::Global<v8::Context>,
  // V8 Map provides identity-based lookup that remains valid if V8 moves an
  // object. Do not key a Rust HashMap by Object::get_identity_hash alone: V8
  // explicitly does not guarantee that those hashes are unique. The map is
  // absent when no host objects are transferred.
  transferred_host_object_ids: Option<v8::Global<v8::Map>>,
}

impl<R> v8::ValueSerializerImpl for V8SerializerDelegate<'_, R>
where
  R: StructuredCloneHostObjectRegistry,
{
  fn throw_data_clone_error<'s>(
    &self,
    scope: &mut v8::PinScope<'s, '_>,
    message: v8::Local<'s, v8::String>,
  ) {
    let error = v8::Exception::error(scope, message);
    scope.throw_exception(error);
  }

  fn has_custom_host_object(&self, _isolate: &v8::Isolate) -> bool {
    // TODO: check collectness
    true
  }

  fn is_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
  ) -> Option<bool> {
    Some(self.host_objects.is_host_object(scope, object))
  }

  fn write_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    object: v8::Local<'s, v8::Object>,
    serializer: &dyn v8::ValueSerializerHelper,
  ) -> Option<bool> {
    // TODO:
    // Need to check detached.
    // https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal
    //
    // 19.1.
    // Otherwise, if value is a platform object that is a serializable object:
    // If value has a [[Detached]] internal slot whose value is true, then throw a "DataCloneError" DOMException.
    let context = v8::Local::new(scope, &self.context);
    let transfer_id = self.transferred_host_object_ids.as_ref().and_then(
      |transferred_host_object_ids| {
        let transferred_host_object_ids =
          v8::Local::new(scope, transferred_host_object_ids);

        transferred_host_object_ids
          .get(scope, object.into())
          .and_then(|value| value.try_cast::<v8::Uint32>().ok())
          .map(|value| value.value())
      },
    );
    self.host_objects.write_host_object(
      scope,
      context,
      object,
      transfer_id,
      serializer,
    )
  }

  // https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/v8_script_value_serializer.cc;l=1023
  fn get_shared_array_buffer_id<'s>(
    &self,
    scope: &mut v8::PinScope<'s, '_>,
    shared_array_buffer: v8::Local<'s, v8::SharedArrayBuffer>,
  ) -> Option<u32> {
    // https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal
    // 13.1.1.2.
    if self.for_storage {
      let message = v8::String::new(
        scope,
        "A SharedArrayBuffer can not be serialized for storage.",
      )?;
      self.throw_data_clone_error(scope, message);
      return None;
    }

    // https://source.chromium.org/chromium/chromium/src/+/main:v8/include/v8-value-serializer.h;l=101-110
    let state = JsRuntime::state_from(scope);
    match &state.shared_array_buffer_store {
      Some(shared_array_buffer_store) => {
        let backing_store = shared_array_buffer.get_backing_store();
        let id = shared_array_buffer_store.insert(backing_store);
        Some(id)
      }
      // A DataCloneError is not thrown since the value cannot be None in the current implementation.
      _ => None,
    }
  }

  // https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/v8_script_value_serializer.cc;l=1061
  fn get_wasm_module_transfer_id(
    &self,
    scope: &mut v8::PinScope<'_, '_>,
    module: v8::Local<v8::WasmModuleObject>,
  ) -> Option<u32> {
    // https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal
    // 13.1.1.2.
    if self.for_storage {
      let message = v8::String::new(
        scope,
        "A WebAssembly.Module can not be serialized for storage.",
      )?;
      self.throw_data_clone_error(scope, message);
      return None;
    }

    let state = JsRuntime::state_from(scope);
    match &state.compiled_wasm_module_store {
      Some(compiled_wasm_module_store) => {
        let compiled_wasm_module = module.get_compiled_module();
        let id = compiled_wasm_module_store.insert(compiled_wasm_module);
        Some(id)
      }
      // A DataCloneError is not thrown since the value cannot be None in the current implementation.
      _ => None,
    }
  }
}

struct V8DeserializerDelegate<'a, R> {
  host_objects: &'a R,
  /// Explicit target realm([v8::Context]) for nested host-object values.
  target_realm: v8::Global<v8::Context>,
  wire_format_version: u32,
  transferred_host_objects: Vec<v8::Global<v8::Object>>,
}

impl<R> v8::ValueDeserializerImpl for V8DeserializerDelegate<'_, R>
where
  R: StructuredCloneHostObjectRegistry,
{
  fn read_host_object<'s, 'i>(
    &self,
    scope: &mut v8::PinScope<'s, 'i>,
    deserializer: &dyn v8::ValueDeserializerHelper,
  ) -> Option<v8::Local<'s, v8::Object>> {
    let target_realm = v8::Local::new(scope, &self.target_realm);
    self.host_objects.read_host_object(
      scope,
      target_realm,
      deserializer,
      self.wire_format_version,
      &self.transferred_host_objects,
    )
  }

  fn get_shared_array_buffer_from_id<'s>(
    &self,
    scope: &mut v8::PinScope<'s, '_>,
    transfer_id: u32,
  ) -> Option<v8::Local<'s, v8::SharedArrayBuffer>> {
    let state = JsRuntime::state_from(scope);
    match &state.shared_array_buffer_store {
      Some(shared_array_buffer_store) => {
        let backing_store = shared_array_buffer_store.take(transfer_id)?;
        let shared_array_buffer =
          v8::SharedArrayBuffer::with_backing_store(scope, &backing_store);
        Some(shared_array_buffer)
      }
      _ => None,
    }
  }

  fn get_wasm_module_from_id<'s>(
    &self,
    scope: &mut v8::PinScope<'s, '_>,
    clone_id: u32,
  ) -> Option<v8::Local<'s, v8::WasmModuleObject>> {
    let state = JsRuntime::state_from(scope);
    match &state.compiled_wasm_module_store {
      Some(compiled_wasm_module_store) => {
        let compiled_module = compiled_wasm_module_store.take(clone_id)?;
        v8::WasmModuleObject::from_compiled_module(scope, &compiled_module)
      }
      _ => None,
    }
  }
}

/// Not a few operation is handled by V8 side.
/// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/value-serializer.cc
/// This abstract operation needs recursible. So almost operation should
/// delegate to [`v8::ValueSerializerImpl`]
///
/// e.g,
///
/// 19.1. If value has a [[Detached]] internal slot whose value is true,
/// then throw a "DataCloneError" DOMException.
/// https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal
///
/// This operation must be implemented within a function that overrides [`v8::ValueSerializerImpl::write_host_object`]
/// function, which is called recursively according to the object graph.
/// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/v8_script_value_serializer.cc;l=499-504
pub fn structured_serialize_internal<'s, 'i, R>(
  scope: &mut v8::PinScope<'s, 'i>,
  value: v8::Local<'s, v8::Value>,
  for_storage: bool,
  host_objects: &R,
) -> Result<Vec<u8>, JsErrorBox>
where
  R: StructuredCloneHostObjectRegistry,
{
  let context = scope.get_current_context();
  serialize_v8_graph(scope, context, value, for_storage, host_objects, &[], &[])
}

enum PreparedTransfer<'s> {
  ArrayBuffer(v8::Local<'s, v8::ArrayBuffer>),
  HostObject(v8::Local<'s, v8::Object>),
}

fn data_clone_error(message: impl Into<String>) -> JsErrorBox {
  JsErrorBox::new("DOMExceptionDataCloneError", message.into())
}

// FIXME:
// Should implement Messageport as a fully Rust CppGc.
//
// This function internally validates the `options` argument for `structuredClone`.
// It must be considered that this function executes within a `MessagePort`.
// https://html.spec.whatwg.org/multipage/structured-data.html#performing-structured-clones-from-other-specifications
// > messagePort.postMessage() uses this pair of abstract operations, as the destination realm is not known until the MessagePort has been shipped.
// https://html.spec.whatwg.org/multipage/web-messaging.html#dom-structuredserializeoptions-transfer
//
// https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializewithtransfer
pub fn structured_serialize_with_transfer<'s, 'i, R>(
  scope: &mut v8::PinScope<'s, 'i>,
  value: v8::Local<'s, v8::Value>,
  transfer_list: &[v8::Local<'s, v8::Value>],
  host_objects: &R,
) -> Result<StructuredSerializeWithTransferResult<R::TransferData>, JsErrorBox>
where
  R: StructuredCloneHostObjectRegistry,
{
  if transfer_list.is_empty() {
    return Ok(StructuredSerializeWithTransferResult {
      serialized: structured_serialize_internal(
        scope,
        value,
        false,
        host_objects,
      )?,
      transfer_data_holders: Vec::new(),
    });
  }

  let context = scope.get_current_context();
  let mut prepared = Vec::with_capacity(transfer_list.len());
  let mut transferred_array_buffers = Vec::new();
  let mut transferred_host_objects = Vec::new();
  let seen = v8::Set::new(scope);

  // 2.
  for transferable in transfer_list.iter().copied() {
    // 1.
    let Ok(object) = transferable.try_cast::<v8::Object>() else {
      return Err(data_clone_error("Cannot transfer type"));
    };
    if !transferable.is_array_buffer()
      && !host_objects.is_transferable_host_object(scope, object)?
    {
      return Err(data_clone_error("Cannot transfer type"));
    }

    // 2.
    if transferable.is_array_buffer() {
      let Ok(array_buffer) = transferable.try_cast::<v8::ArrayBuffer>() else {
        return Err(data_clone_error("Cannot transfer type"));
      };
      if array_buffer.is_shared_array_buffer() {
        return Err(data_clone_error("Cannot transfer shared array buffer"));
      }
      let transfer_id = transferred_array_buffers.len() as u32;
      transferred_array_buffers.push((transfer_id, array_buffer));
      prepared.push(PreparedTransfer::ArrayBuffer(array_buffer));
    } else {
      transferred_host_objects.push(object);
      prepared.push(PreparedTransfer::HostObject(object));
    }

    // 3.
    if seen.has(scope, transferable).unwrap_or(false) {
      return Err(data_clone_error("Cannot transfer value twice"));
    }
    // 4.
    if seen.add(scope, transferable).is_none() {
      return Err(data_clone_error("Cannot index transfer list"));
    }
  }

  // 3.
  let serialized = serialize_v8_graph(
    scope,
    context,
    value,
    false,
    host_objects,
    &transferred_array_buffers,
    &transferred_host_objects,
  )?;

  // TODO: check the collectness
  // A pending V8 exception is represented by the existing empty-buffer
  // sentinel. In particular, do not detach anything on that path.
  if serialized.is_empty() {
    return Ok(StructuredSerializeWithTransferResult {
      serialized,
      transfer_data_holders: Vec::new(),
    });
  }

  // 4.
  let mut transfer_data_holders = Vec::with_capacity(prepared.len());
  // 5.
  for transferable in prepared {
    match transferable {
      // 5.4.
      PreparedTransfer::ArrayBuffer(array_buffer) => {
        if
        // 5.1.
        !array_buffer.is_detachable() || array_buffer.was_detached() {
          return Err(data_clone_error(
            "ArrayBuffer became detached or non-transferable while serializing",
          ));
        }

        // 5.4.1 ~ 5.4.2
        // delegate ArrayBuffer operations to V8
        let backing_store = array_buffer.get_backing_store();
        // 5.4.3.
        if array_buffer.detach(None) != Some(true) {
          return Err(data_clone_error("ArrayBuffer could not be detached"));
        }
        transfer_data_holders
          .push(StructuredCloneTransferData::ArrayBuffer(backing_store));
      }
      // 5.5.
      PreparedTransfer::HostObject(object) => {
        // 5.2.
        if host_objects.was_detached_host_object(scope, object)? {
          return Err(data_clone_error(
            "Host object became detached while serializing",
          ));
        }
        // 5.4.
        let data = host_objects.transfer_host_object(scope, object)?;
        // 5.5.
        host_objects.detach_host_object(scope, object)?;
        transfer_data_holders
          .push(StructuredCloneTransferData::HostObject(data));
      }
    }
  }

  // 6.
  Ok(StructuredSerializeWithTransferResult {
    serialized,
    transfer_data_holders,
  })
}

// TODO: Need to check accurate
// V8 owns the recursive object graph traversal, including reference tracking
// for aliases and cycles. Always produce owned bytes at this intermediate
// layer so the result can be persisted or moved to another isolate. Callers
// such as structuredClone may optimize primitives before reaching here.
fn serialize_v8_graph<'s, 'i, R>(
  scope: &mut v8::PinScope<'s, 'i>,
  context: v8::Local<'s, v8::Context>,
  value: v8::Local<'s, v8::Value>,
  for_storage: bool,
  host_objects: &R,
  transferred_array_buffers: &[(u32, v8::Local<'s, v8::ArrayBuffer>)],
  transferred_host_objects: &[v8::Local<'s, v8::Object>],
) -> Result<Vec<u8>, JsErrorBox>
where
  R: StructuredCloneHostObjectRegistry,
{
  let transferred_host_object_ids = if transferred_host_objects.is_empty() {
    None
  } else {
    let transferred_host_object_ids = v8::Map::new(scope);
    for (transfer_id, object) in transferred_host_objects.iter().enumerate() {
      let transfer_id = u32::try_from(transfer_id)
        .map_err(|_| data_clone_error("Too many host objects to transfer"))?;
      let transfer_id = v8::Integer::new_from_unsigned(scope, transfer_id);
      if transferred_host_object_ids
        .set(scope, (*object).into(), transfer_id.into())
        .is_none()
      {
        return Err(data_clone_error("Cannot index host object transfer"));
      }
    }
    Some(v8::Global::new(scope, transferred_host_object_ids))
  };
  let serializer = v8::ValueSerializer::new(
    scope,
    Box::new(V8SerializerDelegate {
      for_storage,
      host_objects,
      context: v8::Global::new(scope, context),
      transferred_host_object_ids,
    }),
  );
  serializer.write_raw_bytes(&[EMBEDDER_ENVELOPE_TAG]);
  serializer.write_uint32(host_objects.wire_format_version());
  serializer.write_header();
  for (transfer_id, array_buffer) in transferred_array_buffers {
    serializer.transfer_array_buffer(*transfer_id, *array_buffer);
  }

  v8::tc_scope!(let tc_scope, scope);
  let written = serializer.write_value(context, value);
  if tc_scope.has_caught() || tc_scope.has_terminated() {
    tc_scope.rethrow();
    // The pending V8 exception is rethrown by the op dispatcher.
    return Ok(vec![]);
  }
  if written != Some(true) {
    return Err(JsErrorBox::type_error("Failed to serialize value"));
  }

  Ok(serializer.release())
}

/// Not a few operation is handled by V8 side.
/// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/value-serializer.cc
/// This abstract operation needs recursible. So almost operation should
/// delegate to [`v8::ValueDeserializerImpl`]
///
/// e.g,
///
/// 22.2. If the interface identified by interfaceName is not exposed in targetRealm,
/// then throw a "DataCloneError" DOMException.
/// https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserialize
///
/// This operation must be implemented within a function that overrides [`v8::ValueDeserializerImpl::read_host_object`]
/// function, which is called recursively according to the object graph.
/// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/serialization/v8_script_value_deserializer.cc;l=1054-1131
pub fn structured_deserialize<'s, 'i, R>(
  scope: &mut v8::PinScope<'s, 'i>,
  serialized: Vec<u8>,
  target_realm: v8::Local<'s, v8::Context>,
  host_objects: &R,
) -> Result<v8::Local<'s, v8::Value>, JsErrorBox>
where
  R: StructuredCloneHostObjectRegistry,
{
  deserialize_v8_graph(scope, target_realm, &serialized, host_objects, &[], &[])
}

// https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserializewithtransfer
pub fn structured_deserialize_with_transfer<'s, 'i, R>(
  scope: &mut v8::PinScope<'s, 'i>,
  result: StructuredSerializeWithTransferResult<R::TransferData>,
  target_realm: v8::Local<'s, v8::Context>,
  host_objects: &R,
) -> Result<StructuredDeserializeWithTransferResult<'s>, JsErrorBox>
where
  R: StructuredCloneHostObjectRegistry,
{
  if result.transfer_data_holders.is_empty() {
    return Ok(StructuredDeserializeWithTransferResult {
      deserialized: structured_deserialize(
        scope,
        result.serialized,
        target_realm,
        host_objects,
      )?,
      transferred_values: Vec::new(),
    });
  }

  // 2.
  let mut transferred_values =
    Vec::with_capacity(result.transfer_data_holders.len());
  let mut transferred_array_buffers = Vec::new();
  let mut transferred_host_objects = Vec::new();

  // 3.
  for holder in result.transfer_data_holders {
    match holder {
      // 2.
      // 3.
      StructuredCloneTransferData::ArrayBuffer(backing_store) => {
        let array_buffer =
          v8::ArrayBuffer::with_backing_store(scope, &backing_store);
        let transfer_id = transferred_array_buffers.len() as u32;
        transferred_array_buffers.push((transfer_id, array_buffer));
        transferred_values.push(array_buffer.into());
      }
      // 4.
      StructuredCloneTransferData::HostObject(data) => {
        let object =
          host_objects.receive_host_object(scope, target_realm, data)?;
        transferred_host_objects.push(object);
        transferred_values.push(object.into());
      }
    }
  }

  // 4.
  let deserialized = deserialize_v8_graph(
    scope,
    target_realm,
    &result.serialized,
    host_objects,
    &transferred_array_buffers,
    &transferred_host_objects,
  )?;

  Ok(StructuredDeserializeWithTransferResult {
    deserialized,
    transferred_values,
  })
}

fn deserialize_v8_graph<'s, 'i, R>(
  scope: &mut v8::PinScope<'s, 'i>,
  target_realm: v8::Local<'s, v8::Context>,
  bytes: &[u8],
  host_objects: &R,
  transferred_array_buffers: &[(u32, v8::Local<'s, v8::ArrayBuffer>)],
  transferred_host_objects: &[v8::Local<'s, v8::Object>],
) -> Result<v8::Local<'s, v8::Value>, JsErrorBox>
where
  R: StructuredCloneHostObjectRegistry,
{
  let (wire_format_version, bytes) = read_embedder_envelope(bytes)?;
  if wire_format_version == 0
    || wire_format_version > host_objects.wire_format_version()
  {
    return Err(JsErrorBox::range_error(format!(
      "Unsupported structured clone wire format version {wire_format_version}"
    )));
  }
  let deserializer = v8::ValueDeserializer::new(
    scope,
    Box::new(V8DeserializerDelegate {
      host_objects,
      target_realm: v8::Global::new(scope, target_realm),
      wire_format_version,
      transferred_host_objects: transferred_host_objects
        .iter()
        .map(|object| v8::Global::new(scope, *object))
        .collect(),
    }),
    bytes,
  );
  if !deserializer.read_header(target_realm).unwrap_or_default() {
    return Err(JsErrorBox::range_error("Cannot deserialize value header"));
  }
  for (transfer_id, array_buffer) in transferred_array_buffers {
    deserializer.transfer_array_buffer(*transfer_id, *array_buffer);
  }
  deserializer
    .read_value(target_realm)
    .ok_or_else(|| JsErrorBox::range_error("Cannot read deserialize value"))
}

fn read_embedder_envelope(bytes: &[u8]) -> Result<(u32, &[u8]), JsErrorBox> {
  // FIXME:
  // keep backward-compatibility for the permanent external data
  // which handled by Deno.kv (core.serialize/core.derserialize)
  // ext/kv/01_db.ts
  if bytes.first() != Some(&EMBEDDER_ENVELOPE_TAG) {
    return Err(JsErrorBox::range_error(
      "Cannot deserialize structured clone magic",
    ));
  }

  let mut version = 0u32;
  for index in 0..U32_VARINT_MAX_BYTES {
    let byte = *bytes.get(1 + index).ok_or_else(|| {
      JsErrorBox::range_error("Cannot deserialize structured clone version")
    })?;
    let value = byte & VARINT_VALUE_MASK;
    if index == U32_VARINT_MAX_BYTES - 1
      && (value > U32_VARINT_LAST_BYTE_MAX
        || byte & VARINT_CONTINUATION_BIT != 0)
    {
      break;
    }
    version |= (value as u32) << (index * VARINT_VALUE_BITS_PER_BYTE);
    if byte & VARINT_CONTINUATION_BIT == 0 {
      return Ok((version, &bytes[index + 2..]));
    }
  }

  Err(JsErrorBox::range_error(
    "Cannot deserialize structured clone version",
  ))
}

static TRANSFER_STR: crate::FastStaticString = crate::ascii_str!("transfer");

pub struct StructuredSerializeOptions<'s> {
  pub transfer: Vec<v8::Local<'s, v8::Value>>,
}

impl<'s> StructuredSerializeOptions<'s> {
  pub fn convert<'i>(
    scope: &mut v8::PinScope<'s, 'i>,
    value: Option<v8::Local<'s, v8::Value>>,
  ) -> Result<Self, WebIdlError> {
    let Some(value) = value.filter(|value| !value.is_null_or_undefined())
    else {
      return Ok(Self { transfer: vec![] });
    };
    let object = value.try_cast::<v8::Object>().map_err(|_| {
      WebIdlError::new(
        Cow::Borrowed("Failed to execute 'structuredClone'"),
        ContextFn::new_borrowed(&|| Cow::Borrowed("Argument 2")),
        WebIdlErrorKind::ConvertToConverterType("dictionary"),
      )
    })?;
    let key = TRANSFER_STR.v8_string(scope).unwrap();
    let transfer = object
      .get(scope, key.into())
      .unwrap_or_else(|| v8::undefined(scope).into());
    let transfer = if transfer.is_undefined() {
      vec![]
    } else {
      Vec::<v8::Local<'s, v8::Value>>::convert(
        scope,
        transfer,
        Cow::Borrowed("Failed to execute 'structuredClone'"),
        ContextFn::new_borrowed(&|| {
          Cow::Borrowed("'transfer' of 'StructuredSerializeOptions'")
        }),
        &Default::default(),
      )?
    };
    Ok(Self { transfer })
  }
}

#[cfg(test)]
mod tests {
  use super::EMBEDDER_ENVELOPE_TAG;
  use super::StructuredCloneRegistry;
  use super::read_embedder_envelope;
  use super::structured_deserialize;
  use super::structured_serialize_internal;
  use crate::JsRuntime;
  use crate::v8;

  #[test]
  fn intermediate_serialization_encodes_primitives() {
    let mut runtime = JsRuntime::new(Default::default());
    deno_core::scope!(scope, runtime);
    let registry = StructuredCloneRegistry::new();
    let value: v8::Local<v8::Value> = v8::Integer::new(scope, 42).into();
    let bytes =
      structured_serialize_internal(scope, value, false, &registry).unwrap();

    assert!(bytes.starts_with(&[EMBEDDER_ENVELOPE_TAG]));
    let target_realm = scope.get_current_context();
    let value =
      structured_deserialize(scope, bytes, target_realm, &registry).unwrap();
    assert_eq!(value.int32_value(scope), Some(42));
  }

  #[test]
  fn reads_embedder_envelope() {
    let payload = [0xFF, 0x0F];
    let bytes = [[EMBEDDER_ENVELOPE_TAG].as_slice(), &[1], &payload].concat();
    let (version, remaining) = read_embedder_envelope(&bytes).unwrap();
    assert_eq!(version, 1);
    assert_eq!(remaining, payload);

    let bytes = [
      [EMBEDDER_ENVELOPE_TAG].as_slice(),
      &[0xAC, 0x02],
      &payload[..1],
    ]
    .concat();
    let (version, remaining) = read_embedder_envelope(&bytes).unwrap();
    assert_eq!(version, 300);
    assert_eq!(remaining, &payload[..1]);
  }

  #[test]
  fn rejects_invalid_embedder_envelope() {
    assert!(read_embedder_envelope(&[]).is_err());
    assert!(read_embedder_envelope(&[EMBEDDER_ENVELOPE_TAG]).is_err());
    let invalid_version = [
      [EMBEDDER_ENVELOPE_TAG].as_slice(),
      &[0x80, 0x80, 0x80, 0x80, 0x10],
    ]
    .concat();
    assert!(read_embedder_envelope(&invalid_version).is_err());
  }
}

#[cfg(test)]
mod registry_tests {
  use std::cell::Cell;

  use super::*;
  use crate::JsRuntime;

  thread_local! {
    static TEST_TRANSFERABLE_IS_EXPOSED: Cell<bool> = const { Cell::new(true) };
  }

  struct TestTransferable {
    value: u32,
    detached: Cell<bool>,
  }

  // SAFETY: TestTransferable contains no references requiring GC tracing.
  unsafe impl GarbageCollected for TestTransferable {
    fn trace(&self, _visitor: &mut v8::cppgc::Visitor) {}

    fn get_name(&self) -> &'static std::ffi::CStr {
      c"TestTransferable"
    }
  }

  impl WebIdlSerializable for TestTransferable {}
  impl WebIdlTransferable for TestTransferable {}

  impl StructuredCloneDetached for TestTransferable {
    fn was_detached(&self) -> bool {
      self.detached.get()
    }

    fn detach(&self) {
      self.detached.set(true);
    }
  }

  impl StructuredCloneTransferable for TestTransferable {
    type TransferData = u32;

    fn transfer<'s, 'i>(
      &self,
      _scope: &mut v8::PinScope<'s, 'i>,
    ) -> Result<Self::TransferData, JsErrorBox> {
      Ok(self.value)
    }

    fn receive<'s, 'i>(
      _scope: &mut v8::PinScope<'s, 'i>,
      value: Self::TransferData,
    ) -> Result<Self, JsErrorBox> {
      Ok(Self {
        value,
        detached: Cell::new(false),
      })
    }
  }

  impl StructuredCloneHostObject for TestTransferable {
    fn is_exposed<'s, 'i>(
      _scope: &mut v8::PinScope<'s, 'i>,
      _target_realm: v8::Local<'s, v8::Context>,
    ) -> bool {
      TEST_TRANSFERABLE_IS_EXPOSED.get()
    }
  }

  impl StructuredCloneSerializable for TestTransferable {
    fn write_structured_clone_payload<'s, 'i>(
      &self,
      _scope: &mut v8::PinScope<'s, 'i>,
      _context: v8::Local<'s, v8::Context>,
      serializer: &dyn v8::ValueSerializerHelper,
    ) -> Option<bool> {
      serializer.write_uint32(self.value);
      Some(true)
    }

    fn read_structured_clone_payload<'s, 'i>(
      _scope: &mut v8::PinScope<'s, 'i>,
      _context: v8::Local<'s, v8::Context>,
      deserializer: &dyn v8::ValueDeserializerHelper,
      _wire_format_version: u32,
    ) -> Option<Self> {
      let mut value = 0;
      deserializer.read_uint32(&mut value).then_some(Self {
        value,
        detached: Cell::new(false),
      })
    }
  }

  #[test]
  fn resolves_host_object_transfer_reference() {
    const SERIALIZABLE_TAG: u8 = b'}';
    const TRANSFERABLE_TAG: u8 = b'~';

    let mut runtime = JsRuntime::new(Default::default());
    deno_core::scope!(scope, runtime);
    let context = scope.get_current_context();
    let mut registry = StructuredCloneRegistry::new();
    registry.register_serializable_transferable::<TestTransferable>(
      SERIALIZABLE_TAG,
      TRANSFERABLE_TAG,
    );
    let first_source = crate::cppgc::make_cppgc_object(
      scope,
      TestTransferable {
        value: 42,
        detached: Cell::new(false),
      },
    );
    let second_source = crate::cppgc::make_cppgc_object(
      scope,
      TestTransferable {
        value: 43,
        detached: Cell::new(false),
      },
    );
    let graph = v8::Object::new(scope);
    let first_key = v8::String::new(scope, "first").unwrap();
    let alias_key = v8::String::new(scope, "alias").unwrap();
    let second_key = v8::String::new(scope, "second").unwrap();
    assert_eq!(
      graph.set(scope, first_key.into(), first_source.into()),
      Some(true)
    );
    assert_eq!(
      graph.set(scope, alias_key.into(), first_source.into()),
      Some(true)
    );
    assert_eq!(
      graph.set(scope, second_key.into(), second_source.into()),
      Some(true)
    );

    let serialized = structured_serialize_internal(
      scope,
      first_source.into(),
      false,
      &registry,
    )
    .unwrap();
    let cloned = structured_deserialize(scope, serialized, context, &registry)
      .unwrap()
      .try_cast::<v8::Object>()
      .unwrap();
    let cloned_value =
      crate::cppgc::try_unwrap_cppgc_object::<TestTransferable>(
        scope,
        cloned.into(),
      )
      .unwrap();
    assert_eq!(cloned_value.value, 42);
    assert!(!cloned_value.detached.get());

    let result = structured_serialize_with_transfer(
      scope,
      graph.into(),
      &[first_source.into(), second_source.into()],
      &registry,
    )
    .unwrap();
    for source in [first_source, second_source] {
      let source_value = crate::cppgc::try_unwrap_cppgc_object::<
        TestTransferable,
      >(scope, source.into())
      .unwrap();
      assert!(source_value.detached.get());
    }
    {
      v8::tc_scope!(let tc_scope, scope);
      let serialized = structured_serialize_internal(
        tc_scope,
        first_source.into(),
        false,
        &registry,
      )
      .unwrap();
      assert!(serialized.is_empty());
      assert!(tc_scope.has_caught());
    }
    let null = v8::null(scope);
    assert!(
      structured_serialize_with_transfer(
        scope,
        null.into(),
        &[first_source.into()],
        &registry,
      )
      .is_err()
    );

    let result =
      structured_deserialize_with_transfer(scope, result, context, &registry)
        .unwrap();
    assert_eq!(result.transferred_values.len(), 2);
    let cloned_graph = result.deserialized.try_cast::<v8::Object>().unwrap();
    for (key, transfer_id, expected) in
      [(first_key, 0, 42), (alias_key, 0, 42), (second_key, 1, 43)]
    {
      let cloned = cloned_graph
        .get(scope, key.into())
        .unwrap()
        .try_cast::<v8::Object>()
        .unwrap();
      assert_eq!(cloned, result.transferred_values[transfer_id]);
      let cloned_value = crate::cppgc::try_unwrap_cppgc_object::<
        TestTransferable,
      >(scope, cloned.into())
      .unwrap();
      assert_eq!(cloned_value.value, expected);
      assert!(!cloned_value.detached.get());
    }
  }

  #[test]
  fn rejects_host_object_not_exposed_in_target_realm() {
    const SERIALIZABLE_TAG: u8 = b'}';
    const TRANSFERABLE_TAG: u8 = b'~';

    let mut runtime = JsRuntime::new(Default::default());
    deno_core::scope!(scope, runtime);
    let context = scope.get_current_context();
    let mut registry = StructuredCloneRegistry::new();
    registry.register_serializable_transferable::<TestTransferable>(
      SERIALIZABLE_TAG,
      TRANSFERABLE_TAG,
    );

    let serializable = crate::cppgc::make_cppgc_object(
      scope,
      TestTransferable {
        value: 42,
        detached: Cell::new(false),
      },
    );
    let serialized = structured_serialize_internal(
      scope,
      serializable.into(),
      false,
      &registry,
    )
    .unwrap();

    let transferable = crate::cppgc::make_cppgc_object(
      scope,
      TestTransferable {
        value: 43,
        detached: Cell::new(false),
      },
    );
    let transferred = structured_serialize_with_transfer(
      scope,
      transferable.into(),
      &[transferable.into()],
      &registry,
    )
    .unwrap();

    TEST_TRANSFERABLE_IS_EXPOSED.set(false);
    {
      v8::tc_scope!(let tc_scope, scope);
      assert!(
        structured_deserialize(tc_scope, serialized, context, &registry)
          .is_err()
      );
      assert!(tc_scope.has_caught());
    }
    assert!(
      structured_deserialize_with_transfer(
        scope,
        transferred,
        context,
        &registry,
      )
      .is_err()
    );
    TEST_TRANSFERABLE_IS_EXPOSED.set(true);
  }
}
